fluentd-ui/config/routes.rb
Rails.application.routes.draw do
  root "welcome#home"

  resource :daemon, controller: :fluentd do
    get "log"
    get "raw_log"
    get "errors"

    scope module: :fluentd do
      resource :agent, only: [] do
        put "start"
        put "stop"
        put "restart"
        put "reload"
        get "log_tail"
      end

      resource :setting, only: [:show, :edit, :update] do
        get "source_and_output"

        resource :in_tail, only: [:show], module: :settings, controller: :in_tail do
          post "after_file_choose"
          post "after_format"
          post "confirm"
          post "finish"
        end

        resource :in_syslog, only: [:show], module: :settings, controller: :in_syslog do
          post "finish"
        end

        resource :in_monitor_agent, only: [:show], module: :settings, controller: :in_monitor_agent do
          post "finish"
        end

        resource :in_http, only: [:show], module: :settings, controller: :in_http do
          post "finish"
        end

        resource :in_forward, only: [:show], module: :settings, controller: :in_forward do
          post "finish"
        end

        %w(grep parser record_transformer stdout).each do |type|
          resource "filter_#{type}", only: [:show], module: :settings, controller: "filter_#{type}" do
            post "finish"
          end
        end

        resource :out_stdout, only: [:show], module: :settings, controller: :out_stdout do
          post "finish"
        end

        resource :out_mongo, only: [:show], module: :settings, controller: :out_mongo do
          post "finish"
        end

        resource :out_tdlog, only: [:show], module: :settings, controller: :out_tdlog do
          post "finish"
        end

        resource :out_s3, only: [:show], module: :settings, controller: :out_s3 do
          post "finish"
        end

        resource :out_forward, only: [:show], module: :settings, controller: :out_forward do
          post "finish"
        end

        resource :out_elasticsearch, only: [:show], module: :settings, controller: :out_elasticsearch do
          post "finish"
        end

        resources :histories, only: [:index, :show], module: :settings, controller: :histories do
          post "reuse", action: 'reuse', on: :member, as: 'reuse'
          post "configtest" , action: "configtest", on: :member, as: "configtest"
        end

        resources :notes, only: [:update], module: :settings, controller: :notes

        resource :running_backup, only: [:show], module: :settings, controller: :running_backup do
          post "reuse", action: 'reuse', on: :member, as: 'reuse'
          post "configtest" , action: "configtest", on: :member, as: "configtest"
        end
      end
    end
  end

  resource :sessions

  resources :plugins do
    collection do
      get :installed
      get :recommended
      get :updated
      patch :install
      patch :uninstall
      patch :upgrade
      patch :bulk_upgrade
    end
  end

  resource :user, only: [:show, :edit, :update]

  get "misc" => "misc#show"
  get "misc/information"
  post "misc/update_fluentd_ui"
  get "misc/upgrading_status"
  get "misc/download_info"

  namespace :polling do
    get "alerts"
  end

  namespace :tutorials do
    get "/" => :index
    get "chapter1"
    get "chapter2"
    get "chapter3"
    get "chapter4"
    get "chapter5"
    get "log_tail"
    post "request_fluentd"
  end

  namespace :api do
    get "tree"
    get "file_preview"
    post "regexp_preview"

    resources :settings, only: [:index, :show, :update, :destroy], defaults: { format: "json" }
    resources :config_definitions, only: [:index], defaults: { format: "json" }
  end
end

fluentd-ui/app/models/concerns/fluentd/setting/configurable.rb
class Fluentd
  module Setting
    module Configurable
      extend ActiveSupport::Concern

      included do
        class_attribute :_types, :_defaults, :_secrets, :_aliases, :_required
        class_attribute :_deprecated_params, :_obsoleted_params, :_descriptions
        class_attribute :_list, :_value_types, :_symbolize_keys
        class_attribute :_argument_name, :_built_in_params, :_sections, :_section_params
        self._types = {}
        self._defaults = {}
        self._secrets = {}
        self._aliases = {}
        self._required = {}
        self._deprecated_params = {}
        self._obsoleted_params = {}
        self._descriptions = {}
        self._list = {}
        self._value_types = {}
        self._symbolize_keys = {}
        self._argument_name = nil
        self._built_in_params = []
        self._sections = {}
        self._section_params = Hash.new {|h, k| h[k] = [] }
      end

      def initialize(attributes = {})
        # the superclass does not know specific attributes of the model
        begin
          super
        rescue ActiveModel::UnknownAttributeError => ex
          Rails.logger.warn(ex)
        end
        self.class._sections.each do |name, klass|
          klass.init
          if klass.multi
            next if attributes.nil?
            next if attributes[name].nil?
            attributes[name].each do |attr|
              next unless attr
              attr.each do |index, _attr|
                self._section_params[name] << klass.new(_attr)
              end
            end
          else
            attr = attributes.dig(name, "0")
            self._section_params[name] << klass.new(attr) if attr
          end
        end
      end

      module ClassMethods
        # config_param :name, :string, default: "value", secret: true
        def config_param(name, type = ActiveModel::Type::Value.new, **options)
          # NOTE: We cannot overwrite types defined by ActiveModel in config/initializers/types.rb
          if type == :time
            type = Fluentd::Setting::Type::Time.new
          end
          if name.to_s.start_with?("@")
            _name = name.to_s[1..-1]
            config_param(_name.to_sym, type, **options.merge(alias: name))
            self._built_in_params << _name
          elsif ["id", "type", "log_level"].include?(name.to_s)
            self._built_in_params << name
            unless name == "type"
              attribute(name, type, **options.slice(:precision, :limit, :scale))
            end
          else
            attribute(name, type, **options.slice(:precision, :limit, :scale))
          end
          self._types[name] = type
          self._descriptions[name] = options[:desc] if options.key?(:desc)
          self._defaults[name] = options[:default] if options.key?(:default)
          self._secrets[name] = options[:secret] if options.key?(:secret)
          self._aliases[name] = options[:alias] if options.key?(:alias)
          self._required[name] = options[:required] if options.key?(:required)
          self._deprecated_params[name] = options[:deprecated] if options.key?(:deprecated)
          self._obsoleted_params[name] = options[:obsoleted] if options.key?(:obsoleted)
          self._list[name] = options[:list] if options.key?(:list)
          self._value_types[name] = options[:value_types] if options.key?(:value_types)
          self._symbolize_keys = options[:symbolize_keys] if options.key?(:symbolize_keys)
        end

        def config_section(name, **options, &block)
          if self._sections.key?(name)
            self._sections[name].merge(**options, &block)
          else
            attribute(name, :section)
            section_class = Class.new(::Fluentd::Setting::Section)
            section_class.section_name = name
            section_class.required = options[:required]
            section_class.multi = options[:multi]
            section_class.alias = options[:alias]
            section_class._block = block
            self.const_set(name.to_s.classify, section_class)
            self._sections[name] = section_class
          end
        end

        def config_argument(name, type = ActiveModel::Type::Value.new, **options)
          config_param(name, type, **options)
          set_argument_name(name)
        end

        def set_argument_name(name)
          self._argument_name = name
        end
      end
    end
  end
end

fluentd-ui/app/models/concerns/fluentd/setting/formatter_advanced_options.rb
class Fluentd
  module Setting
    module FormatterAdvancedOptions
      extend ActiveSupport::Concern

      def advanced_options
        [
          :time_type,
          :time_format,
          :timezone,
          :utc,
        ]
      end

      def hidden_options
        [
          :localtime
        ]
      end
    end
  end
end

fluentd-ui/app/models/concerns/fluentd/setting/label.rb
class Fluentd
  module Setting
    module Label
      extend ActiveSupport::Concern

      included do
        config_param(:label, :string)
      end
    end
  end
end

fluentd-ui/app/models/concerns/fluentd/setting/parser_advanced_options.rb
class Fluentd
  module Setting
    module ParserAdvancedOptions
      extend ActiveSupport::Concern

      def advanced_options
        [
          :types,
          :null_value_pattern,
          :null_empty_string,
          :estimate_current_event,
          :time_key,
          :time_type,
          :time_format,
          :keep_time_key,
          :utc,
        ]
      end

      def hidden_options
        [
          :localtime
        ]
      end
    end
  end
end

fluentd-ui/app/models/concerns/fluentd/setting/pattern.rb
class Fluentd
  module Setting
    module Pattern
      extend ActiveSupport::Concern

      included do
        config_argument(:pattern, :string)
      end
    end
  end
end

fluentd-ui/app/models/concerns/fluentd/setting/plugin.rb
require "fluent/plugin"
require "fluent/plugin/buf_file"
require "fluent/test/log"
require "fluent/test/driver/input"
require "fluent/test/driver/output"
require "fluent/test/driver/filter"
require "fluent/test/driver/parser"
require "fluent/test/driver/formatter"

class Fluentd
  module Setting
    module Plugin
      extend ActiveSupport::Concern

      include ActiveModel::Model
      include ActiveModel::Attributes
      include Fluentd::Setting::Configurable
      include Fluentd::Setting::PluginConfig
      include Fluentd::Setting::SectionParser
      include Fluentd::Setting::PluginParameter

      included do
        cattr_accessor :plugin_type, :plugin_name, :config_definition
      end

      module ClassMethods
        def register_plugin(type, name)
          self.plugin_type = type
          self.plugin_name = name

          if ["filter", "output"].include?(type)
            include Fluentd::Setting::Pattern
          end

          if ["input", "filter", "output"].include?(type)
            include Fluentd::Setting::Label
          end

          if ["parser"].include?(type)
            include Fluentd::Setting::ParserAdvancedOptions
          end

          if ["formatter"].include?(type)
            include Fluentd::Setting::FormatterAdvancedOptions
          end

          self.load_plugin_config do |_name, params|
            params.each do |param_name, definition|
              if definition[:section]
                parse_section(param_name, definition)
                if %i(buffer storage parse format).include?(param_name)
                  attribute("#{param_name}_type", :string)
                end
              else
                config_param(param_name, definition[:type] || self._types[param_name], **definition.except(:type))
              end
            end
          end
        end

        def load_plugin_config
          dumped_config = {}
          plugin_class.ancestors.reverse_each do |klass|
            next unless klass.respond_to?(:dump_config_definition)
            dumped_config_definition = klass.dump_config_definition
            dumped_config[klass.name] = dumped_config_definition unless dumped_config_definition.empty?
          end
          self.config_definition = dumped_config
          dumped_config.each do |name, config|
            yield name, config
          end
        end

        def plugin_instance
          @plugin_instance ||= Fluent::Plugin.__send__("new_#{plugin_type}", plugin_name)
        end

        def plugin_class
          @plugin_class ||= plugin_instance.class
        end

        def create_driver(config)
          case plugin_type
          when "input"
            if plugin_class.class_variable_defined?(:@@pos_file_paths)
              plugin_class.class_variable_set(:@@pos_file_paths, {})
            end
            Fluent::Test::Driver::Input.new(plugin_class).configure(config)
          when "output"
            if Fluent::Plugin::FileBuffer.class_variable_defined?(:@@buffer_paths)
              Fluent::Plugin::FileBuffer.class_variable_set(:@@buffer_paths, {})
            end
            Fluent::Test::Driver::Output.new(plugin_class).configure(config)
          when "filter"
            Fluent::Test::Driver::Filter.new(plugin_class).configure(config)
          when "parser"
            Fluent::Test::Driver::Parser.new(plugin_class).configure(config)
          when "formatter"
            FLuent::Test::Driver::Formatter.new(plugin_class).configure(config)
          else
            nil
          end
        end

        def plugin_helpers
          @plugin_helpers ||= if plugin_instance.respond_to?(:plugin_helpers)
                                plugin_instance.plugin_helpers
                              else
                                []
                              end
        end

        def section?
          false
        end
      end
    end
  end
end

fluentd-ui/app/models/concerns/fluentd/setting/plugin_config.rb
class Fluentd
  module Setting
    module PluginConfig
      extend ActiveSupport::Concern

      included do
        validate :validate_configuration
      end

      def validate_configuration
        original_log = $log
        $log = DummyLogger.logger
        full_config = to_config.to_s
        config = if full_config.start_with?("<label ")
                   full_config.lines[2..-3].join
                 else
                   full_config.lines[1..-2].join
                 end
        self.class.create_driver(config)
      rescue Fluent::ConfigError => ex
        errors.add(:base, :invalid, message: ex.message)
      ensure
        $log = original_log
      end

      def to_config
        name = case plugin_type
               when "input"
                 "source"
               when "output"
                 "match"
               when "filter"
                 "filter"
               when "parser"
                 "parse"
               when "formatter"
                 "format"
               when "buffer"
                 "buffer"
               when "storage"
                 "storage"
               end
        _attributes = attributes.reject do |key, value|
          %w(parse_type format_type buffer_type storage_type).include?(key.to_s)
        end
        _attributes = { "@type" => self.plugin_name }.merge(_attributes)
        _attributes["@log_level"] = _attributes.delete("log_level")
        label = _attributes.delete("label")
        if plugin_type == "input"
          _attributes["@label"] = label
        end
        argument = case plugin_type
                   when "output", "filter", "buffer"
                     _attributes.delete(self._argument_name.to_s) || ""
                   else
                     ""
                   end
        attrs, elements = parse_attributes(_attributes)
        case plugin_type
        when "output", "filter"
          # e is <match> or <filter>
          e = config_element(name, argument, attrs, elements)
          if label.blank?
            e
          else
            config_element("label", label, {}, [e])
          end
        else
          config_element(name, argument, attrs, elements)
        end
      end

      def parse_attributes(attributes)
        base_klasses = config_definition.keys
        sections, params = attributes.partition do |key, _section_attributes|
          base_klasses.any? do |base_klass|
            config_definition.dig(base_klass, key.to_sym, :section) || config_definition.dig(key.to_sym, :section)
          end
        end
        elements = []
        sections.to_h.each do |key, section_params|
          next if section_params.blank?
          section_class = self._sections[key.to_sym]
          if %w(parse format buffer storage).include?(key)
            if section_params && section_params.key?("0")
              section_params["0"] = { "type" => self.attributes["#{key}_type"] }.merge(section_params["0"])
            else
              section_params = {
                "0" => { "type" => self.attributes["#{key}_type"] }
              }
            end
          end
          _elements = section_params.map do |index, _section_params|
            section_class.new(_section_params).to_config
          end.compact
          elements.concat(_elements)
        end
        params = params.to_h
        if plugin_type == "filter" && plugin_name == "record_transformer"
          record_params = {}
          params.delete("record").lines.each do |line|
            k, v = line.split(" ", 2)
            record_params[k] = v
          end
          elements << config_element("record", "", record_params, [])
        end
        attrs = params.reject do |key, value|
          skip?(key.to_sym, value)
        end
        return attrs, elements
      end

      # copy from Fluent::Test::Helpers#config_element
      def config_element(name = 'test', argument = '', params = {}, elements = [])
        Fluent::Config::Element.new(name, argument, params, elements)
      end

      def skip?(key, value)
        return true if value.blank?
        if self._defaults.key?(key)
          self.class.reformat_value(key, self._defaults[key]) == self.class.reformat_value(key, value)
        else
          false
        end
      end
    end
  end
end

fluentd-ui/app/views/fluentd/_form.html.haml
.col-xl-6
  - @fluentd.errors.full_messages.each do |e|
    .alert.alert-danger= e

  = form_for(:fluentd, url: url, method: method) do |f|
    .form-group
      = f.label :variant
      = f.hidden_field :variant
      = @fluentd.variant
    .form-group
      = f.label :pid_file
      - if @fluentd.td_agent?
        = f.text_field :pid_file, class: "form-control", disabled: true
        = f.hidden_field :pid_file
      - else
        = f.text_field :pid_file, class: "form-control"
    .form-group
      = f.label :log_file
      - if @fluentd.td_agent?
        = f.text_field :log_file, class: "form-control", disabled: true
        = f.hidden_field :log_file
      - else
        = f.text_field :log_file, class: "form-control"
    .form-group
      = f.label :config_file
      - if @fluentd.td_agent?
        = f.text_field :config_file, class: "form-control", disabled: true
        = f.hidden_field :config_file
      - else
        = f.text_field :config_file, class: "form-control"
    .form-group
      = f.label :note
      = f.text_field :note, class: "form-control"
    = f.submit btn, class: "btn btn-primary"

fluentd-ui/app/views/fluentd/edit.html.haml
- page_title t('.page_title')

= render partial: "form", locals: { btn: t("terms.update"), url: daemon_path(@fluentd), method: :patch }

fluentd-ui/app/views/fluentd/errors.html.haml
- page_title t('fluentd.common.recent_errors', days: @error_duration_days) do
  - link_to raw_log_daemon_path(@fluentd), class: "btn btn-primary float-right mt-3" do
    = icon('fa-download')
    = t('fluentd.common.raw_log_link')

.row
  .col-xl-12.col-sm-12
    - @errors.each do |error|
      .card.card-primary
        .card-header
          %h4= error[:subject]
        - if error[:notes].present?
          .card-body
            %ul
              - error[:notes].each do |stack|
                %li= stack
    - if @errors.empty?
      %p= t('.error_is_empty')

fluentd-ui/app/views/fluentd/log.html.haml
- page_title t('.page_title', label: @fluentd.label) do
  - link_to raw_log_daemon_path(@fluentd), class: "btn btn-primary float-right mt-3" do
    = icon('fa-download')
    = t('fluentd.common.raw_log_link')

.row.ml-3
  = preserve do # partial containing <pre>, so shouldn't break indent
    = render partial: "shared/vue/fluent_log", locals: { fluentd: @fluentd }

fluentd-ui/app/views/fluentd/new.html.haml
- page_title t('.page_title')

= render partial: "form", locals: { btn: t("terms.create"), url: daemon_path, method: :post }

fluentd-ui/app/views/fluentd/show.html.haml
- if @fluentd.present?
  - page_title t('.page_title')
  .row
    .col-xl-6.col-sm-6
      %div{class: "card card-#{@fluentd.agent.running? ? "primary":"secondary"}"}
        .card-header
          %h4
            - if @fluentd.agent.running?
              = icon("fa-play")
              = t("fluentd.common.running")
            - else
              = icon("fa-pause")
              = t("fluentd.common.stopped")
        .card-body
          - if flash[:error]
            .alert.alert-danger= flash[:error]
          = link_to icon("fa-play") << t("fluentd.common.start"), start_daemon_agent_path(@fluentd),     method: :put, class: "btn #{@fluentd.agent.running? ? "disabled btn-outline-dark" : "btn-primary"}"
          = link_to icon("fa-pause") << t("fluentd.common.stop"), stop_daemon_agent_path(@fluentd),       method: :put, class: "btn #{@fluentd.agent.running? ? "btn-danger" : "disabled btn-outline-dark"}"
          = link_to icon("fa-refresh") << t("fluentd.common.restart"), restart_daemon_agent_path(@fluentd), method: :put, class: "btn #{@fluentd.agent.running? ? "btn-warning" : "disabled btn-outline-dark"}"
          = link_to icon("fa-refresh") << t("fluentd.common.reload"), reload_daemon_agent_path(@fluentd), method: :put, class: "btn #{@fluentd.agent.running? ? "btn-info" : "disabled btn-outline-dark"}"
    .col-xl-6.col-sm-6
      .card.card-default
        .card-header
          .float-right
            = link_to t('terms.edit'), edit_daemon_path, class: "btn btn-info"
            = link_to t('terms.destroy'), "#", class: "btn btn-danger", data: { toggle: "modal", target: "#setting-destroy-modal" }
          %h4= t('fluentd.common.fluentd_info')
          .modal.fade{id: "setting-destroy-modal"}
            .modal-dialog
              .modal-content
                .modal-header
                  %button.close{"data-dismiss" => "modal"}
                    = raw "&times;"
                  %h4.modal-title
                    = t('fluentd.common.destroy_fluentd_setting', brand: fluentd_ui_brand)
                .modal-body
                  = raw t('fluentd.common.destroy_fluentd_setting_warning', brand: fluentd_ui_brand)
                .modal-footer
                  = form_tag(daemon_path(@fluentd), method: :delete) do
                    %button.btn.btn-secondary{"data-dismiss" => "modal"}
                      Close
                    = submit_tag t('terms.destroy'), class: "btn btn-danger"

        %table.table.table-hover.mb-0
          %tbody
            %tr
              %th= @fluentd.class.human_attribute_name(:pid_file)
              %td= @fluentd.agent.pid_file
            %tr
              %th= @fluentd.class.human_attribute_name(:log_file)
              %td= @fluentd.agent.log_file
            %tr
              %th= @fluentd.class.human_attribute_name(:config_file)
              %td= @fluentd.agent.config_file
            %tr
              %th= @fluentd.class.human_attribute_name(:note)
              %td= @fluentd.note
  .row
    .col-xl-12
      = preserve do # partial containing <pre>, so shouldn't break indent
        = render partial: "shared/vue/fluent_log", locals: { fluentd: @fluentd }

- else
  = render partial: "shared/initial_setup"